Have smoke tests fail when API is disabled, as they depend on it

diff --git a/jobs/smoke-tests/templates/bin/run b/jobs/smoke-tests/templates/bin/run
--- a/jobs/smoke-tests/templates/bin/run
+++ b/jobs/smoke-tests/templates/bin/run
@@ -6,22 +6,29 @@
     end
 
     traefik = link("traefik")
+    if not traefik.p('traefik.api.enabled') # Smoke tests do require the API to be activated
+-%>
+echo "ERROR: smoke tests require the API to be enabled." \
+    "Please set the 'traefik.api.enabled' property of the 'teraefik' job to 'true'. Aborting."
+exit 1
+<%
+    else # if p('traefik.api.enabled')
 
-    adm_username = traefik.p("traefik.api.digest_auth.username")
-    adm_password = traefik.p("traefik.api.digest_auth.password")
+        adm_username = traefik.p("traefik.api.digest_auth.username")
+        adm_password = traefik.p("traefik.api.digest_auth.password")
 
-    if traefik.p("traefik.tls.enabled")
-        pxy_scheme = "https"
-        pxy_port = traefik.p("traefik.tls.port")
-    else
-        pxy_scheme = "http"
-        pxy_port = traefik.p("traefik.http.port")
-    end
+        if traefik.p("traefik.tls.enabled")
+            pxy_scheme = "https"
+            pxy_port = traefik.p("traefik.tls.port")
+        else
+            pxy_scheme = "http"
+            pxy_port = traefik.p("traefik.http.port")
+        end
 
-    api_tls_port = traefik.p("traefik.api.tls.port")
+        api_tls_port = traefik.p("traefik.api.tls.port")
 
-    main_address = traefik.instances.first.address
-    frontend_hostname = p("frontend_hostname")
+        main_address = traefik.instances.first.address
+        frontend_hostname = p("frontend_hostname")
 -%>
 
 set -eo pipefail
@@ -197,3 +204,6 @@ proxy_https GET "/request?toto=titi&tata=tutu" \
 echo $'\n'
 
 exit 0
+<%
+    end # if p('traefik.api.enabled')
+-%>
